name: "Fosstars (Security)"
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: ~

jobs:
  create_fosstars_report:
    runs-on: ubuntu-latest
    name: "Open Source Security"
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: SAP/fosstars-rating-core-action@v1.3.0
        with:
          rating: security
          report-branch: fosstars-security-report
          report-file: README.md
          badge-file: fosstars_security_rating.svg
          token: "${{ secrets.OSPO_GITHUB_TOKEN }}"
