name: "Fosstars (OSS Rules of Play)"
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: ~

jobs:
  create_fosstars_report:
    runs-on: ubuntu-latest
    name: "Open Source Rules of Play (beta)"
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./.github/actions/oss-rules-of-play-action
        with:
          rating: oss-rules-of-play
          fosstars-version: v1.4.0
          report-branch: fosstars
          token: "${{ secrets.OSPO_GITHUB_TOKEN }}"
